{% set version = "1.3-0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nor1mix
  version: {{ version|replace("-", "_") }}

source:
  fn: nor1mix_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/nor1mix_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/nor1mix/nor1mix_{{ version }}.tar.gz
  sha256: 9ce4ee92f889a4a4041b5ea1ff09396780785a9f12ac46f40647f74a37e327a0

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('nor1mix')"  # [not win]
    - "\"%R%\" -e \"library('nor1mix')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=nor1mix
  license: GPL (>= 2)
  summary: Onedimensional Normal Mixture Models Classes, for, e.g., density estimation or clustering
    algorithms research and teaching; providing the widely used Marron-Wand densities.  Efficient
    random number generation and graphics; now fitting to data by ML (Maximum Likelihood)
    or EM estimation.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
