{% set version = "1.3-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nor1mix
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nor1mix_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nor1mix/nor1mix_{{ version }}.tar.gz
  sha256: 97bfd0f8c847fa68bf607aaa465845a34ac8a7a262315073026a6a1937dd076e

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('nor1mix')"           # [not win]
    - "\"%R%\" -e \"library('nor1mix')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=nor1mix
  license: GPL-2.0-or-later
  summary: Onedimensional Normal Mixture Models Classes, for, e.g., density estimation or clustering algorithms research and teaching; providing the widely used Marron-Wand densities.  Efficient random number generation and graphics; now fitting to data by ML (Maximum Likelihood) or EM estimation.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
