appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: I6jVeiOh4FMz25BW1e6DawJ0DU504u+vru7Hx0tYwQw2ck64E1tasCZ/8195Sb6t9FopPeMu0M9+0f/Zpm0VIEyUA8htGyTIunA7hmfkLnaLdQScNWrIKWtv2IMtjz1s0fywSefMgAgYWcvNXdWN4+k46EQkmlS2wHE18rBZsFxB5SuB43p1GuEBxyuxZ4kyUrqFhoN1pYMJJ7vxFB/ZwRNrj2O99UsdZ2MJiuIhfoKdYcaZB3oNonTRrKLViQWdfQ/tiF/FDm/aDhMmH7gIWb/fs1dkMo3jPT5EkLS2o9TDx6LccNL1d/ptNGiZBpysbeWIfOPTALRXCxYDnAOpGrFaT0BGFTad950BaaN58MGtvSedleRv2tWaZXerEP/VRmFuKJP8De2w7Y86j5n4gINdFCwK4l4jkBSNBnaYwOUD/k2LVyY+5Ba53r9PTFEnZ2GJRIdgVORBZrHZJDwT0HfjEITegYZcaMyoWla2VLBODgnreE1O0dlIXNpW6mpdfosuXLEbSRpk4zkIyhm7aqhJZl6S0njXhrMICP4dO2xmii2VziCXAN0xHuOvUAymaGqJkXDlbiufre5V09gBCrOVXSlAWpQqM5lTmD5Cx1VpORBMFsFfjIYw5wZiWxDzgLLRtuPe/4S3kbRNo6rTZtAcVE99SXBCkExccaT4MaE=}
